config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#index'
  resources :users, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :phone_number, presence: true
  validates :phone_number, format: { with: /\d{4}-\d{4}/,
    message: "Phone number doesn't match valid format (XXXX-XXXX)" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :phone_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NexoosTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <%= link_to root_path, class: "navbar-brand" do %>
    <p>Home</p>
  <% end %>

  <div class="navbar-right hidden-xs hidden-sm">
    <%= link_to "New user", new_user_path, class: "navbar-item navbar-link" %>
    <%= link_to "All users", users_path, class: "navbar-item navbar-link" %>
  </div>

  <div class="navbar-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu">
        <li><%= link_to "New user", new_user_path %></li>
        <li><%= link_to "All users", users_path %></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <table class="users-table">
        <tr class="table-head">
          <th>Name</th>
          <th>Phone Number</th>
        </tr>
        <div class="users">
          <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.phone_number %></td>
            </tr>
          <% end %>
        </div>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="form">
        <%= form_for @user do |f| %>
          <% if @user.errors.any? %>
            <ul class="list-unstyled alert alert-danger">
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <br>
              <% end %>
            </ul>
          <% end %>
          <%= f.text_field :name, placeholder: "Name", class: "form-control" %>
          <%= f.text_field :phone_number, placeholder: "Phone number", class: "form-control" %>
          <%= f.submit class: "btn btn-block btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>